# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKSdQw3YwMgVXC9LGEsNkKUIjpsAvM6-
"""

!pip install -q transformers pillow

from transformers import pipeline
from google.colab import files
from PIL import Image

# 1. Load the pipeline
print("Loading the AI... please wait a moment...")
caption_helper = pipeline("image-text-to-text", model="Salesforce/blip-image-captioning-base")
print("AI is ready!")

# 2. Pop up a button to upload your image
print("\nClick 'Choose Files' below to upload your picture:")
uploaded_files = files.upload()

# 3. Process the image
if uploaded_files:
    image_filename = list(uploaded_files.keys())[0]
    my_image = Image.open(image_filename)

    print("\nThe AI is thinking...")

    # FIX: We now provide a starting text prompt so the pipeline doesn't throw an error!
    ai_results = caption_helper(my_image, text="a picture of")

    # Extract the text sentence from the AI's answer
    generated_caption = ai_results[0]['generated_text']

    print("\n" + "="*30)
    print("🤖 AI Caption:", generated_caption)
    print("="*30)
else:
    print("You didn't upload any file!")
